version: '3.1'

services:
  datasource:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'finance-app'
