version: '3.6'

networks:
  finance-app:
    driver: bridge

x-api: &api
  working_dir: /usr/api
  volumes:
    - ./apps/api:/usr/api
  ports:
    - 3333:3333
  networks:
    - finance-app
  depends_on:
    - datasource

services:
  workspace:
    build: .
    working_dir: /usr/workspace
    volumes:
      - .:/usr/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: finance-app-workspace
    networks:
      - finance-app

  api:
    <<: *api
    container_name: finance-app-api
    build:
      context: ./apps/api
      target: dev-api
    ports:
    - 3333:3333
    # depends_on:
    #   - api-migration

  api-migration:
    <<: *api
    build:
      context: ./apps/api
      target: dev-migration
    ports:
    - 3332:3332

  web:
    build: 
      context: ./apps/web
      target: dev
    working_dir: /usr/web
    volumes:
      - ./apps/web:/usr/web
    networks:
      - finance-app
    ports:
      - 3000:3000
    container_name: finance-app-web
    depends_on:
      - api
      - datasource

  datasource:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - finance-app
    environment:
      POSTGRES_PASSWORD: 'app'
      POSTGRES_USER: 'finance'
      POSTGRES_DB: 'finance-app'
